version: "3.9"

services:
  web:
    tty: true
    build: ./app
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8001:8001
    env_file:
      - .env.dev
    depends_on:
      - db
      - redis
    restart: "unless-stopped"
  db:
    image: postgres:14.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=nocode
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=superuser
  redis:
    image: redis:alpine
  celery:
    restart: always
    build: ./app
    command: celery -A config worker -l info
    volumes:
      - ./app/:/usr/src/app/
    env_file:
      - .env.dev
    depends_on:
      - redis
  celery-beat:
    build: ./app
    command: celery -A config beat -l info
    volumes:
      - ./app/:/usr/src/app/
    env_file:
      - .env.dev
    depends_on:
      - redis

volumes:
  postgres_data:
