# Generated by Django 4.0.4 on 2022-06-14 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_version', models.CharField(max_length=10, unique=True)),
                ('release_notes', models.TextField()),
                ('released_at', models.DateTimeField(auto_now_add=True)),
                ('current_release', models.BooleanField(default=False, editable=False)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='syntax.release')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReleaseSyntax',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('model_type', models.CharField(max_length=30)),
                ('syntax_json', models.JSONField(blank=True, default=list)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syntax', to='syntax.release')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReleaseChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('change_type', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=10)),
                ('model_type', models.CharField(max_length=30)),
                ('syntax_json', models.JSONField()),
                ('parent_release', models.ForeignKey(help_text='Release this change is being made against.', on_delete=django.db.models.deletion.CASCADE, related_name='release_changes', to='syntax.release')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
