# Generated by Django 4.0.4 on 2022-05-31 11:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('syntax', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyntaxDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('syntax_type', models.CharField(max_length=10)),
                ('syntax_json', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Syntax',
        ),
    ]
