# Generated by Django 4.0.4 on 2022-05-31 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('syntax', '0003_syntaxdefinition_object_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_version', models.CharField(max_length=10)),
                ('release_notes', models.TextField()),
                ('released_at', models.DateTimeField(auto_now_add=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='syntax.release')),
                ('released_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReleaseChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('syntax_json', models.JSONField()),
                ('release_version', models.PositiveIntegerField()),
                ('object_id', models.UUIDField(default=uuid.uuid4, editable=False, null=True)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='syntax.release')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='SyntaxDefinition',
        ),
    ]
