# Generated by Django 4.0.4 on 2022-05-31 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('syntax', '0004_release_releasechange_delete_syntaxdefinition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='released_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
