# Generated by Django 4.0.4 on 2022-05-31 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syntax', '0006_alter_release_released_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='release_version',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
