# Generated by Django 4.0.4 on 2022-06-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syntax', '0009_release_current_release'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='functions',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='release',
            name='modelschemas',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='release',
            name='packages',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='release',
            name='pages',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='release',
            name='workflows',
            field=models.JSONField(default=dict),
        ),
    ]
