# Generated by Django 4.0.4 on 2022-06-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syntax', '0010_alter_release_functions_alter_release_modelschemas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='functions',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='release',
            name='modelschemas',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='release',
            name='packages',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='release',
            name='pages',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='release',
            name='workflows',
            field=models.JSONField(default=list),
        ),
    ]
