# Generated by Django 4.0.4 on 2022-06-01 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('syntax', '0011_alter_release_functions_alter_release_modelschemas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releasechange',
            name='release',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='syntax.release'),
        ),
    ]
