# Generated by Django 4.0.4 on 2022-06-01 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('syntax', '0012_alter_releasechange_release'),
    ]

    operations = [
        migrations.AddField(
            model_name='releasechange',
            name='parent_release',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='staged_changes', to='syntax.release'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='releasechange',
            name='release',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='committed_changed', to='syntax.release'),
        ),
    ]
