# Generated by Django 4.0.4 on 2022-06-07 12:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('syntax', '0014_alter_releasechange_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releasechange',
            name='object_id',
            field=models.UUIDField(default=uuid.UUID('91a52880-4581-4971-b020-3473774f840b'), editable=False, null=True),
        ),
    ]
