# Generated by Django 4.0.4 on 2022-06-07 12:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('syntax', '0016_alter_release_functions_alter_release_modelschemas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releasechange',
            name='object_id',
            field=models.UUIDField(default=uuid.UUID('408e0f51-5a93-4c47-afd3-4cd56592e86c'), editable=False),
        ),
    ]
