# Generated by Django 4.0.4 on 2022-06-07 12:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('syntax', '0018_alter_releasechange_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='current_release',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='releasechange',
            name='object_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
