# Generated by Django 4.0.4 on 2022-06-07 12:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('syntax', '0019_alter_release_current_release_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releasechange',
            name='object_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
