# Generated by Django 4.0.4 on 2022-06-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syntax', '0020_alter_releasechange_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releasechange',
            name='object_id',
            field=models.UUIDField(editable=False),
        ),
    ]
