# Generated by Django 4.0.4 on 2022-06-07 13:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('syntax', '0021_alter_releasechange_object_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseSyntax',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('model_type', models.CharField(max_length=30)),
                ('syntax_json', models.JSONField(blank=True, default=list)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syntax', to='syntax.release')),
            ],
        ),
        migrations.AddConstraint(
            model_name='releasesyntax',
            constraint=models.UniqueConstraint(fields=('release', 'model_type'), name='unique_release_syntax_type'),
        ),
    ]
