# Generated by Django 4.0.4 on 2022-06-07 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syntax', '0022_releasesyntax_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='release',
            name='functions',
        ),
        migrations.RemoveField(
            model_name='release',
            name='modelschemas',
        ),
        migrations.RemoveField(
            model_name='release',
            name='packages',
        ),
        migrations.RemoveField(
            model_name='release',
            name='pages',
        ),
        migrations.RemoveField(
            model_name='release',
            name='workflows',
        ),
    ]
