# Generated by Django 4.0.4 on 2022-05-07 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='model',
        ),
    ]
