# Generated by Django 4.0.4 on 2022-05-07 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='page',
            name='layout_page_content_5f242f_idx',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='content_type',
            new_name='model',
        ),
        migrations.RemoveField(
            model_name='page',
            name='resource_id',
        ),
    ]
