# Generated by Django 4.0.4 on 2022-05-06 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('models', '0001_initial'),
        ('layout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='models.model'),
        ),
    ]
