# Generated by Django 4.0.4 on 2022-05-07 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('layout', '0002_remove_page_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['content_type', 'object_id'], name='layout_page_content_2fd8f8_idx'),
        ),
    ]
