# Generated by Django 4.0.4 on 2022-05-13 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
        ('layout', '0002_remove_page_layout_page_content_5f242f_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='model_schema',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='db.modelschema'),
            preserve_default=False,
        ),
    ]
