# Generated by Django 4.0.4 on 2022-05-24 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0003_page_model_schema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='model',
        ),
    ]
