# Generated by Django 4.0.4 on 2022-05-06 11:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dynamic_models', '0003_alter_fieldschema_id_alter_modelschema_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('model_name', models.CharField(max_length=255)),
                ('model_schema', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='dynamic_models.modelschema')),
            ],
        ),
        migrations.AddIndex(
            model_name='model',
            index=models.Index(fields=['model_name'], name='models_mode_model_n_d07c73_idx'),
        ),
    ]
